### ISSUE TITLE
Visual studio code - Cannot find module @/respositories/person or its corresponding declarations

### ISSUE THREAD

**Issue by inspiraller** [gokulchandra/ts-path-resolution#8]
Steps:
- git clone project
- cd ts-path-resolution
- npm i
- npm run build
- npm test
- open visual studio code and look at test/services/person/index.spec.ts file 
```
{
	"resource": ".../ts-path-resolution/test/services/person/index.spec.ts",
	"owner": "typescript",
	"code": "2307",
	"severity": 8,
	"message": "Cannot find module '@/services/person' or its corresponding type declarations.",
	"source": "ts",
	"startLineNumber": 2,
	"startColumn": 41,
	"endLineNumber": 2,
	"endColumn": 60
}
```

## from:
```
src
test
```
## to 
```
src/test
```

I am not quite understanding why that is, and how is it possible to get test folder to work the same when its not inside src/ folder.

**Comment by gokulchandra** [comment]
Hey @inspiraller , thank you for reporting this issue. 

This seems to be related to how VSC handles and interprets `tsconfig.json`. You could try the suggestions specified in this issue: https://github.com/microsoft/vscode/issues/94474#issuecomment-610527471. 
Hope that helps!

**Comment by christopher-caldwell** [comment]
@inspiraller Here's what worked for me in VS Code. I added another `tsconfig.json` to the root of `test/`, with the following config:

```json
{
  "compilerOptions": {
// different
    "baseUrl": "../src",
    "paths": {
      "@/*": ["*"],
      "database": ["lib/database/index.ts"]
    },
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "./dist",
    "target": "es6"
  },
  "exclude": ["node_modules"],
// different
  "include": ["../**/*"] 
}

```

Intellisense was able to pickup the definitions without issue, after.
